        // Galaxy and destination metadata. Loaded before waves.js so route helpers can read GALAXY_DEFINITIONS.
        const GALAXY_DEFINITIONS = Object.freeze([
            {
                id: 'neon-rift',
                title: 'BINARY QUASAR',
                name: 'BINARY QUASAR',
                subtitle: 'BULLET FLIGHT',
                desc: 'Binary debris, tight lanes, fast formations.',
                available: true,
                colors: ['#dcecff', '#8fa7c9', '#ffffff'],
                coreColor: '#ffffff',
                glyphs: ['1', '0'],
                coreGlyph: '0',
                coreVoidGlyph: '1',
                visualStyle: 'binaryQuasar',
                arms: 3,
                tilt: 0.48,
                twist: 2.8,
                seed: 11
            },
            {
                id: 'void-circuit',
                title: 'MATRIX NEBULA',
                name: 'MATRIX NEBULA',
                subtitle: 'NODE CRAWLER',
                desc: 'Room nodes, robot patrols, route choices, cache rewards.',
                available: true,
                mode: 'matrixCrawler',
                colors: ['#007a3a', '#25b85b', '#f2fff6'],
                coreColor: '#f2fff6',
                glyphs: [
                    '\uFF66', '\uFF67', '\uFF68', '\uFF69', '\uFF6A', '\uFF6B', '\uFF6C', '\uFF6D',
                    '\uFF6E', '\uFF6F', '\uFF70', '\uFF71', '\uFF72', '\uFF73', '\uFF74', '\uFF75',
                    '\uFF76', '\uFF77', '\uFF78', '\uFF79', '\uFF7A', '\uFF7B', '\uFF7C', '\uFF7D',
                    '\uFF7E', '\uFF7F', '\uFF80', '\uFF81', '\uFF82', '\uFF83', '\uFF84', '\uFF85',
                    '\uFF86', '\uFF87', '\uFF88', '\uFF89', '\uFF8A', '\uFF8B', '\uFF8C', '\uFF8D',
                    '\uFF8E', '\uFF8F', '\uFF90', '\uFF91', '\uFF92', '\uFF93', '\uFF94', '\uFF95',
                    '\uFF96', '\uFF97', '\uFF98', '\uFF99', '\uFF9A', '\uFF9B', '\uFF9C', '\uFF9D',
                    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
                    'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
                    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                    '+', '-', '*', '/', '\\', '=', '<', '>', ':', ';', '.', '|'
                ],
                coreGlyph: '\uFF8A',
                coreVoidGlyph: '\uFF90',
                visualStyle: 'matrixNebula',
                arms: 2,
                tilt: 0.38,
                twist: 3.55,
                seed: 29
            },
            {
                id: 'rose-quasar',
                title: 'FRACTAL HALO',
                name: 'FRACTAL HALO',
                desc: 'Locked. Gravity wells, curved shots, halo hazards.',
                available: false,
                mode: 'fractalGravity',
                colors: ['#ff7ab8', '#8fb8ff', '#fff0fa'],
                coreColor: '#fff0fa',
                glyphs: ['{', '}', '(', ')', '∞', '∂', '∑', '.'],
                coreGlyph: '∞',
                coreVoidGlyph: '∂',
                visualStyle: 'fractalHalo',
                arms: 4,
                tilt: 0.58,
                twist: 2.35,
                seed: 47
            },
            {
                id: 'amber-halo',
                title: 'KERNEL CORONA',
                name: 'KERNEL CORONA',
                desc: 'Locked. Thermal lanes, memory blocks, bus traffic.',
                available: false,
                colors: ['#ff8a1c', '#ff5f00', '#7cc7ff'],
                coreColor: '#7cc7ff',
                glyphs: ['#', '/', '\\', '|', '[', ']', '{', '}'],
                coreGlyph: '#',
                coreVoidGlyph: '|',
                visualStyle: 'kernelEye',
                arms: 2,
                tilt: 0.52,
                twist: 2.95,
                seed: 73
            },
            {
                id: 'glass-nebula',
                title: 'TENSOR MIRAGE',
                name: 'TENSOR MIRAGE',
                desc: 'Locked. Mirrored signals, false depth, phase drift.',
                available: false,
                colors: ['#6aa8ff', '#ff5e8a', '#dcecff'],
                coreColor: '#dcecff',
                glyphs: [
                    '\u2297', '\u03BB', '\u2207', '\u2202', '\u03A3', '\u0394', '\u03C0', '\u00D7',
                    'x', 'y', 'z', 'w', 'i', 'j', 'k', 'T', 'M', '[]', '<>', '::', '//', 'x/y'
                ],
                coreGlyph: '\u2297',
                coreVoidGlyph: '\u03BB',
                visualStyle: 'tensorMirage',
                arms: 5,
                tilt: 0.44,
                twist: 1.95,
                seed: 101
            },
            {
                id: 'red-dwarf',
                title: 'BITSHIFT DWARF',
                name: 'BITSHIFT DWARF',
                subtitle: 'VECTOR SCROLL',
                desc: 'Operator lanes, overflow debris, horizontal pressure.',
                available: true,
                mode: 'bitshiftScroller',
                campaignSourceGalaxyIndex: 1,
                colors: ['#ff4f4a', '#ff9a73', '#fff1e8'],
                coreColor: '#fff1e8',
                glyphs: ['<', '>', '^', 'v', '/', '\\', '0', '1'],
                coreGlyph: '>',
                coreVoidGlyph: '<',
                visualStyle: 'bitshiftSphere',
                arms: 3,
                tilt: 0.62,
                twist: 3.2,
                seed: 137
            },
            {
                id: 'prism-array',
                title: 'PRISM ARRAY',
                name: 'PRISM ARRAY',
                subtitle: 'SURVIVAL RUN',
                desc: 'High swarm density, locked camera, continuous auto-fire.',
                available: true,
                mode: 'survivor',
                visualStyle: 'prismArray',
                colors: ['#61f7ff', '#ffe66d', '#ff5edb', '#7cff9b', '#ffffff'],
                coreColor: '#ffffff',
                glyphs: ['▲', '▶', '▼', '◀', '⯅', '⯆', '⯇', '⯈', '▴', '▸', '▾', '◂'],
                coreGlyph: '▲',
                coreVoidGlyph: '▼',
                arms: 6,
                tilt: 0.72,
                twist: 4.4,
                seed: 211
            },
            {
                id: 'vector-terminal',
                title: 'TERMINAL',
                name: 'TERMINAL',
                desc: 'Hull telemetry, ship comparison, launch-frame selection.',
                available: true,
                mode: 'shipHub',
                visualStyle: 'shipHub',
                colors: ['#8ff7ff', '#6aa8ff', '#ffe66d', '#ffffff'],
                coreColor: '#f6fbff',
                glyphs: ['[', ']', '=', '|', '+', 'A', 'I', 'R'],
                coreGlyph: 'A',
                coreVoidGlyph: '+',
                arms: 2,
                tilt: 0.34,
                twist: 1.2,
                seed: 307
            }
        ]);
